### ISSUE TITLE
How to use this as a preprocess for rollup/webpack

### ISSUE THREAD

**Issue by zwz** [boomla/turbo.css.js#13]
I am quite interested in turbo.css.
I want to use it in my project, which is bundled by rollup.
I wonder if it is possible to have the compiler work the same as `scss` or `postcss` in the building toolset.

**Comment by zupa-hu** [comment]
It can absolutely used with bundlers, though I'm not aware of a rollup plugin.
I'm using it with Esbuild myself in a codebase.

If you don't need CSS namespacing, the Turbo related build boils down to:

```js
let turbo = new Turbo();
// for every file in the codebase that may contain Turbo CSS source, run:
turbo.addSource(fileContent)
// The final CSS can be extracted from the Turbo compiler instance
let css = turbo.css();
// Make sure to also load the base CSS styles
```

**Comment by zupa-hu** [comment]
If you do need namespacing, you need to rewrite each Turbo CSS snippet one by one to have the namespace injected.

```js
// for each file content as fileContent
fileContent = replaceTurboSnippets(fileContent, (snippet: string) => {
	return turbo.add(snippet);
});
```

Other than that, same as in my previous comment.

See the test cases for examples on how to use a namespace.
https://github.com/boomla/turbo.css.js/blob/master/src/Turbo_test.ts

**Comment by zwz** [comment]
Thank you for your instructions. I will try it.
But it really helps turbo.css to be adopted widely with such a plugin.

**Comment by zupa-hu** [comment]
Well, I agree, I just don't have the time to do it.

Maybe you could share your solution if it works out for you? I'm happy to link to any resources from the README as well - or just have it here.
